name: streetfightermemo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_riverpod:
  freezed_annotation:
  cupertino_icons: ^1.0.2
  go_router:
  csv: ^5.0.2
  asset_fill: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner:
  riverpod_generator:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - Image/
    - assets/blanka/
    - assets/cammy/
    - assets/chun-li/
    - assets/dee jay/
    - assets/dhalsim/
    - assets/e.honda/
    - assets/guile/
    - assets/jamie/
    - assets/jp/
    - assets/juri/
    - assets/ken/
    - assets/kimberly/
    - assets/lily/
    - assets/luke/
    - assets/manon/
    - assets/marisa/
    - assets/ryu/
    - assets/zangief/
